export const currencyFlags = {
  'DZD': '🇩🇿', 'ARS': '🇦🇷', 'AWG': '🇦🇼', 'AUD': '🇦🇺',
  'BSD': '🇧🇸', 'BHD': '🇧🇭', 'BDT': '🇧🇩', 'BBD': '🇧🇧',
  'BZD': '🇧🇿', 'BMD': '🇧🇲', 'BTN': '🇧🇹', 'BOB': '🇧🇴',
  'BWP': '🇧🇼', 'BND': '🇧🇳', 'BIF': '🇧🇮', 'CVE': '🇨🇻',
  'KHR': '🇰🇭', 'CAD': '🇨🇦', 'KYD': '🇰🇾', 'CLP': '🇨🇱',
  'CNY': '🇨🇳', 'COP': '🇨🇴', 'KMF': '🇰🇲', 'CRC': '🇨🇷',
  'HRK': '🇭🇷', 'CUP': '🇨🇺', 'DKK': '🇩🇰', 'DJF': '🇩🇯',
  'DOP': '🇩🇴', 'EGP': '🇪🇬', 'SVC': '🇸🇻', 'SZL': '🇸🇿',
  'ETB': '🇪🇹', 'EUR': '🇪🇺', 'FKP': '🇫🇰', 'GMD': '🇬🇲',
  'GIP': '🇬🇮', 'GBP': '🇬🇧', 'GTQ': '🇬🇹', 'GNF': '🇬🇳',
  'GYD': '🇬🇾', 'HTG': '🇭🇹', 'HNL': '🇭🇳', 'HKD': '🇭🇰',
  'HUF': '🇭🇺', 'ISK': '🇮🇸', 'INR': '🇮🇳', 'IDR': '🇮🇩',
  'IQD': '🇮🇶', 'ILS': '🇮🇱', 'JMD': '🇯🇲', 'JPY': '🇯🇵',
  'JOD': '🇯🇴', 'KZT': '🇰🇿', 'KES': '🇰🇪', 'KPW': '🇰🇵',
  'KWD': '🇰🇼', 'LAK': '🇱🇦', 'LVL': '🇱🇻', 'LBP': '🇱🇧',
  'LSL': '🇱🇸', 'LRD': '🇱🇷', 'LYD': '🇱🇾', 'LTL': '🇱🇹',
  'MOP': '🇲🇴', 'MWK': '🇲🇼', 'MYR': '🇲🇾', 'MVR': '🇲🇻',
  'MRO': '🇲🇷', 'MUR': '🇲🇺', 'MNT': '🇲🇳', 'MAD': '🇲🇦',
  'MMK': '🇲🇲', 'NZD': '🇳🇿', 'NIO': '🇳🇮', 'NGN': '🇳🇬',
  'NOK': '🇳🇴', 'OMR': '🇴🇲', 'PKR': '🇵🇰', 'XPD': '🏳️',
  'PAB': '🇵🇦', 'PGK': '🇵🇬', 'PYG': '🇵🇾', 'PEN': '🇵🇪',
  'PHP': '🇵🇭', 'QAR': '🇶🇦', 'RUB': '🇷🇺', 'WST': '🇼🇸',
  'SAR': '🇸🇦', 'SCR': '🇸🇨', 'SLL': '🇸🇱', 'SGD': '🇸🇬',
  'SBD': '🇸🇧', 'SOS': '🇸🇴', 'ZAR': '🇿🇦', 'LKR': '🇱🇰',
  'SEK': '🇸🇪', 'CHF': '🇨🇭', 'SYP': '🇸🇾', 'TWD': '🇹🇼',
  'TZS': '🇹🇿', 'THB': '🇹🇭', 'TTD': '🇹🇹', 'TND': '🇹🇳',
  'AED': '🇦🇪', 'USD': '🇺🇸', 'VUV': '🇻🇺', 'VND': '🇻🇳',
  'ZMK': '🇿🇲'
};

export const getCurrencyFlag = (currency) => currencyFlags[currency] || '🏳️';

export const currencySymbols = {
  DZD: 'د.ج', ARS: 'AR$', AWG: 'Afl', AUD: 'A$',
  BSD: 'B$', BHD: 'BD', BDT: '৳', BBD: 'Bds$',
  BZD: 'BZ$', BMD: 'BD$', BTN: 'Nu', BOB: 'Bs',
  BWP: 'P', BND: 'B$', BIF: 'FBu', CVE: 'Esc',
  KHR: '៛', CAD: 'C$', KYD: 'CI$', CLP: 'CL$',
  CNY: '¥', COP: 'CO$', KMF: 'CF', CRC: '₡',
  HRK: 'kn', CUP: '₱', DKK: 'kr', DJF: 'Fdj',
  DOP: 'RD$', EGP: 'E£', SVC: '₡', SZL: 'E',
  ETB: 'Br', EUR: '€', FKP: 'FK£', GMD: 'D',
  GIP: '£', GBP: '£', GTQ: 'Q', GNF: 'FG',
  GYD: 'G$', HTG: 'G', HNL: 'L', HKD: 'HK$',
  HUF: 'Ft', ISK: 'kr', INR: '₹', IDR: 'Rp',
  IQD: 'ع.د', ILS: '₪', JMD: 'J$', JPY: '¥',
  JOD: 'JD', KZT: '₸', KES: 'KSh', KPW: '₩',
  KWD: 'KD', LAK: '₭', LVL: 'Ls', LBP: 'L£',
  LSL: 'M', LRD: 'L$', LYD: 'LD', LTL: 'Lt',
  MOP: 'MOP$', MWK: 'MK', MYR: 'RM', MVR: 'Rf',
  MRO: 'UM', MUR: '₨', MNT: '₮', MAD: 'MAD',
  MMK: 'K', NZD: 'NZ$', NIO: 'C$', NGN: '₦',
  NOK: 'kr', OMR: 'ر.ع', PKR: '₨', XPD: 'XPD',
  PAB: 'B/', PGK: 'K', PYG: '₲', PEN: 'S/',
  PHP: '₱', QAR: 'QR', RUB: '₽', WST: 'WS$',
  SAR: 'SR', SCR: '₨', SLL: 'Le', SGD: 'S$',
  SBD: 'SI$', SOS: 'Sh', ZAR: 'R', LKR: '₨',
  SEK: 'kr', CHF: 'CHF', SYP: 'S£', TWD: 'NT$',
  TZS: 'TSh', THB: '฿', TTD: 'TT$', TND: 'DT',
  AED: 'د.إ', USD: '$', VUV: 'VT', VND: '₫',
  ZMK: 'ZK',
};

export const getCurrencySymbol = (currency) => currencySymbols[currency] || '';
