export const currencyFlags = {
  'DZD': '🇩🇿', 'ARS': '🇦🇷', 'AWG': '🇦🇼', 'AUD': '🇦🇺',
  'BSD': '🇧🇸', 'BHD': '🇧🇭', 'BDT': '🇧🇩', 'BBD': '🇧🇧',
  'BZD': '🇧🇿', 'BMD': '🇧🇲', 'BTN': '🇧🇹', 'BOB': '🇧🇴',
  'BWP': '🇧🇼', 'BND': '🇧🇳', 'BIF': '🇧🇮', 'CVE': '🇨🇻',
  'KHR': '🇰🇭', 'CAD': '🇨🇦', 'KYD': '🇰🇾', 'CLP': '🇨🇱',
  'CNY': '🇨🇳', 'COP': '🇨🇴', 'KMF': '🇰🇲', 'CRC': '🇨🇷',
  'HRK': '🇭🇷', 'CUP': '🇨🇺', 'DKK': '🇩🇰', 'DJF': '🇩🇯',
  'DOP': '🇩🇴', 'EGP': '🇪🇬', 'SVC': '🇸🇻', 'SZL': '🇸🇿',
  'ETB': '🇪🇹', 'EUR': '🇪🇺', 'FKP': '🇫🇰', 'GMD': '🇬🇲',
  'GIP': '🇬🇮', 'GBP': '🇬🇧', 'GTQ': '🇬🇹', 'GNF': '🇬🇳',
  'GYD': '🇬🇾', 'HTG': '🇭🇹', 'HNL': '🇭🇳', 'HKD': '🇭🇰',
  'HUF': '🇭🇺', 'ISK': '🇮🇸', 'INR': '🇮🇳', 'IDR': '🇮🇩',
  'IQD': '🇮🇶', 'ILS': '🇮🇱', 'JMD': '🇯🇲', 'JPY': '🇯🇵',
  'JOD': '🇯🇴', 'KZT': '🇰🇿', 'KES': '🇰🇪', 'KPW': '🇰🇵',
  'KWD': '🇰🇼', 'LAK': '🇱🇦', 'LVL': '🇱🇻', 'LBP': '🇱🇧',
  'LSL': '🇱🇸', 'LRD': '🇱🇷', 'LYD': '🇱🇾', 'LTL': '🇱🇹',
  'MOP': '🇲🇴', 'MWK': '🇲🇼', 'MYR': '🇲🇾', 'MVR': '🇲🇻',
  'MRO': '🇲🇷', 'MUR': '🇲🇺', 'MNT': '🇲🇳', 'MAD': '🇲🇦',
  'MMK': '🇲🇲', 'NZD': '🇳🇿', 'NIO': '🇳🇮', 'NGN': '🇳🇬',
  'NOK': '🇳🇴', 'OMR': '🇴🇲', 'PKR': '🇵🇰', 'XPD': '🏳️',
  'PAB': '🇵🇦', 'PGK': '🇵🇬', 'PYG': '🇵🇾', 'PEN': '🇵🇪',
  'PHP': '🇵🇭', 'QAR': '🇶🇦', 'RUB': '🇷🇺', 'WST': '🇼🇸',
  'SAR': '🇸🇦', 'SCR': '🇸🇨', 'SLL': '🇸🇱', 'SGD': '🇸🇬',
  'SBD': '🇸🇧', 'SOS': '🇸🇴', 'ZAR': '🇿🇦', 'LKR': '🇱🇰',
  'SEK': '🇸🇪', 'CHF': '🇨🇭', 'SYP': '🇸🇾', 'TWD': '🇹🇼',
  'TZS': '🇹🇿', 'THB': '🇹🇭', 'TTD': '🇹🇹', 'TND': '🇹🇳',
  'AED': '🇦🇪', 'USD': '🇺🇸', 'VUV': '🇻🇺', 'VND': '🇻🇳',
  'ZMK': '🇿🇲'
};

export const getCurrencyFlag = (currency) => currencyFlags[currency] || '🏳️';
